services:
  vite:
    build:
      context: .
      dockerfile: Dockerfile
    image: vite-nginx:latest
    env_file:
      - .env
    deploy:
      replicas: ${INSTANCES}
    restart: always
    networks:
      - vite-networks

  nginx:
    image: nginx:1.27.2
    volumes:
      - ./nginx.docker.conf:/etc/nginx/nginx.conf # Mount custom Nginx configuration
      - nginx-logs:/var/log/nginx # Use a named volume for Nginx logs
    ports:
      - "80:80"
    deploy:
      replicas: 1 # Ensure only one instance of Nginx runs
      restart_policy:
        condition: on-failure # Restart on failure
    networks:
      - vite-networks

networks:
  vite-networks:
    driver: bridge

volumes:
  nginx-logs: # Define the named volume for Nginx logs
